import type { Metadata } from "next";
import { Nunito, PT_Serif, PT_Sans } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/ReduxProvider";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const ptSans = PT_Sans({
  variable: "--font-pt-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const ptSerif = PT_Serif({
  variable: "--font-pt-serif",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${ptSans.variable} ${ptSerif.variable} relative antialiased`}
      >
        <div className="texture" />
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
